/**
 * Секция 2: Образование и квалификация
 * 7 подсекции
 */

import { PortfolioSectionDefinition } from "@/types";
import * as OPTIONS from "../field-options";

export const SECTION_2_EDUCATION: PortfolioSectionDefinition = {
  sectionId: "section-2",
  title: "Образование и квалификация",
  description: "Образование, специалности и професионални квалификации",
  order: 2,
  subsections: [
    // 2.1. Образование и специалности (record_list)
    {
      subsectionId: "education",
      sectionId: "section-2",
      type: "record_list",
      title: "Образование и специалности",
      description: "Придобито образование",
      order: 1,
      displayMode: "table",
      allowMultipleRecords: true,
      endpoint: {
        cmd: "education",
        method: "POST",
      },
      fields: [
        {
          key: "mesec_from",
          label: "Месец от",
          type: "number",
          required: false,
          min: 1,
          max: 12,
        },
        {
          key: "godina_from",
          label: "Година от",
          type: "number",
          required: true,
          min: 1950,
          max: 2100,
        },
        {
          key: "now_to",
          label: "До сега",
          type: "checkbox",
          required: false,
        },
        {
          key: "mesec_to",
          label: "Месец до",
          type: "number",
          required: false,
          min: 1,
          max: 12,
        },
        {
          key: "godina_to",
          label: "Година до",
          type: "number",
          required: false,
          min: 1950,
          max: 2100,
        },
        {
          key: "type",
          label: "Тип на образованието",
          type: "select",
          required: true,
          options: OPTIONS.EDUCATION_TYPES,
        },
        {
          key: "institution",
          label: "Обучителна институция",
          type: "text",
          required: true,
          maxLength: 150,
        },
        {
          key: "specialty",
          label: "Специалност",
          type: "text",
          required: true,
          maxLength: 150,
        },
      ],
    },

    // 2.2. Специалности (direct_fields)
    {
      subsectionId: "specialties",
      sectionId: "section-2",
      type: "direct_fields",
      title: "Специалности",
      description: "Професионални квалификации",
      order: 2,
      endpoint: {
        cmd: "portfolio",
        method: "POST",
      },
      fields: [
        {
          key: "specialty",
          label: "Професионална квалификация / специалност",
          type: "text",
          required: false,
          maxLength: 150,
        },
        {
          key: "teacher",
          label: 'Професионална квалификация "учител"',
          type: "select",
          required: false,
          options: OPTIONS.YES_NO_OPTIONS,
        },
        {
          key: "specialty2",
          label: "Професионална квалификация / специалност 2",
          type: "text",
          required: false,
          maxLength: 150,
        },
        {
          key: "teacher2",
          label: 'Професионална квалификация "учител" 2',
          type: "select",
          required: false,
          options: OPTIONS.YES_NO_OPTIONS,
        },
        {
          key: "specialty3",
          label: "Професионална квалификация / специалност 3",
          type: "text",
          required: false,
          maxLength: 150,
        },
        {
          key: "teacher3",
          label: 'Професионална квалификация "учител" 3',
          type: "select",
          required: false,
          options: OPTIONS.YES_NO_OPTIONS,
        },
        {
          key: "specialty4",
          label: "Професионална квалификация / специалност 4",
          type: "text",
          required: false,
          maxLength: 150,
        },
        {
          key: "teacher4",
          label: 'Професионална квалификация "учител" 4',
          type: "select",
          required: false,
          options: OPTIONS.YES_NO_OPTIONS,
        },
        {
          key: "specialty5",
          label: "Професионална квалификация / специалност 5",
          type: "text",
          required: false,
          maxLength: 100,
        },
        {
          key: "teacher5",
          label: 'Професионална квалификация "учител" 5',
          type: "select",
          required: false,
          options: OPTIONS.YES_NO_OPTIONS,
        },
      ],
    },

    // 2.3. Професионални квалификации (record_list)
    {
      subsectionId: "professional-qualifications",
      sectionId: "section-2",
      type: "record_list",
      title: "Професионални квалификации",
      description: "ПКС и професионални квалификации",
      order: 3,
      displayMode: "table",
      allowMultipleRecords: true,
      endpoint: {
        cmd: "professional",
        method: "POST",
      },
      fields: [
        {
          key: "mesec_from",
          label: "Месец от",
          type: "number",
          required: false,
          min: 1,
          max: 12,
        },
        {
          key: "godina_from",
          label: "Година от",
          type: "number",
          required: true,
          min: 1950,
          max: 2100,
        },
        {
          key: "now_to",
          label: "До сега",
          type: "checkbox",
          required: false,
        },
        {
          key: "mesec_to",
          label: "Месец до",
          type: "number",
          required: false,
          min: 1,
          max: 12,
        },
        {
          key: "godina_to",
          label: "Година до",
          type: "number",
          required: false,
          min: 1950,
          max: 2100,
        },
        {
          key: "name",
          label: "Наименование",
          type: "text",
          required: true,
          maxLength: 150,
        },
        {
          key: "specialty",
          label: "Специалност",
          type: "text",
          required: true,
          maxLength: 150,
        },
        {
          key: "pks",
          label: "ПКС",
          type: "select",
          required: true,
          options: OPTIONS.PKS_LEVELS,
        },
        {
          key: "hours",
          label: "Брой академични часове",
          type: "text",
          required: true,
          maxLength: 50,
        },
        {
          key: "institution",
          label: "Обучителна институция",
          type: "text",
          required: true,
          maxLength: 150,
        },
      ],
    },

    // 2.4. Квалификационни кредити (record_list)
    {
      subsectionId: "credits",
      sectionId: "section-2",
      type: "record_list",
      title: "Квалификационни кредити",
      description: "Получени квалификационни кредити",
      order: 4,
      displayMode: "table",
      allowMultipleRecords: true,
      endpoint: {
        cmd: "credits",
        method: "POST",
      },
      fields: [
        {
          key: "tema",
          label: "Име на обучението",
          type: "text",
          required: true,
          maxLength: 255,
        },
        {
          key: "institution",
          label: "Обучителна институция",
          type: "text",
          required: true,
          maxLength: 150,
        },
        {
          key: "quantity",
          label: "Брой кредити",
          type: "select",
          required: true,
          options: OPTIONS.CREDIT_QUANTITIES,
        },
        {
          key: "duration",
          label: "Продължителност",
          type: "select",
          required: true,
          options: OPTIONS.CREDIT_DURATIONS,
        },
        {
          key: "mesec",
          label: "Месец",
          type: "number",
          required: true,
          min: 1,
          max: 12,
        },
        {
          key: "godina",
          label: "Година",
          type: "number",
          required: true,
          min: 1950,
          max: 2100,
        },
      ],
    },

    // 2.5. Вътрешни квалификации (record_list)
    {
      subsectionId: "internal-qualifications",
      sectionId: "section-2",
      type: "record_list",
      title: "Вътрешни квалификации",
      description: "Вътрешни училищни квалификации",
      order: 5,
      displayMode: "table",
      allowMultipleRecords: true,
      endpoint: {
        cmd: "internal",
        method: "POST",
      },
      fields: [
        {
          key: "institution",
          label: "Вътрешна институция",
          type: "text",
          required: true,
          maxLength: 150,
        },
        {
          key: "name",
          label: "Наименование",
          type: "text",
          required: true,
          maxLength: 150,
        },
        {
          key: "hours",
          label: "Брой академични часове",
          type: "text",
          required: true,
          maxLength: 50,
        },
        {
          key: "mesec_from",
          label: "Месец от",
          type: "number",
          required: false,
          min: 1,
          max: 12,
        },
        {
          key: "godina_from",
          label: "Година от",
          type: "number",
          required: true,
          min: 1950,
          max: 2100,
        },
        {
          key: "now_to",
          label: "До сега",
          type: "checkbox",
          required: false,
        },
        {
          key: "mesec_to",
          label: "Месец до",
          type: "number",
          required: false,
          min: 1,
          max: 12,
        },
        {
          key: "godina_to",
          label: "Година до",
          type: "number",
          required: false,
          min: 1950,
          max: 2100,
        },
      ],
    },

    // 2.6. Други квалификации (record_list)
    {
      subsectionId: "other-qualifications",
      sectionId: "section-2",
      type: "record_list",
      title: "Други квалификации",
      description: "Семинари, конференции и други обучения",
      order: 6,
      displayMode: "table",
      allowMultipleRecords: true,
      endpoint: {
        cmd: "qualifications",
        method: "POST",
      },
      fields: [
        {
          key: "name",
          label: "Наименование",
          type: "text",
          required: true,
          maxLength: 150,
        },
        {
          key: "type",
          label: "Тип",
          type: "select",
          required: true,
          options: OPTIONS.QUALIFICATION_TYPES,
        },
        {
          key: "institution",
          label: "Обучителна институция",
          type: "text",
          required: true,
          maxLength: 150,
        },
        {
          key: "mesec_from",
          label: "Месец от",
          type: "number",
          required: false,
          min: 1,
          max: 12,
        },
        {
          key: "godina_from",
          label: "Година от",
          type: "number",
          required: true,
          min: 1950,
          max: 2100,
        },
        {
          key: "now_to",
          label: "До сега",
          type: "checkbox",
          required: false,
        },
        {
          key: "mesec_to",
          label: "Месец до",
          type: "number",
          required: false,
          min: 1,
          max: 12,
        },
        {
          key: "godina_to",
          label: "Година до",
          type: "number",
          required: false,
          min: 1950,
          max: 2100,
        },
      ],
    },

    // 2.7. Чужди езици (record_list)
    {
      subsectionId: "languages",
      sectionId: "section-2",
      type: "record_list",
      title: "Чужди езици",
      description: "Чуждоезикови умения",
      order: 7,
      displayMode: "table",
      allowMultipleRecords: true,
      endpoint: {
        cmd: "languages",
        method: "POST",
      },
      fields: [
        {
          key: "language",
          label: "Език",
          type: "select",
          required: true,
          options: OPTIONS.LANGUAGES,
        },
        {
          key: "level",
          label: "Ниво на владеене",
          type: "select",
          required: true,
          options: OPTIONS.LANGUAGE_LEVELS,
        },
      ],
    },
  ],
};
