/**
 * Секция 5: Участие и членство
 * 6 подсекции
 */

import { PortfolioSectionDefinition } from "@/types";
import * as OPTIONS from "../field-options";

export const SECTION_5_PARTICIPATION: PortfolioSectionDefinition = {
  sectionId: "section-5",
  title: "Участие и членство",
  description: "Програми, проекти и професионални организации",
  order: 5,
  subsections: [
    // 5.1. Участие в програми (record_list)
    {
      subsectionId: "programs",
      sectionId: "section-5",
      type: "record_list",
      title: "Участие в програми",
      description: "Национални и международни програми",
      order: 1,
      displayMode: "table",
      allowMultipleRecords: true,
      endpoint: {
        cmd: "programs",
        method: "POST",
      },
      fields: [
        {
          key: "mesec_from",
          label: "Месец от",
          type: "number",
          required: true,
          min: 1,
          max: 12,
        },
        {
          key: "godina_from",
          label: "Година от",
          type: "number",
          required: true,
          min: 1950,
          max: 2100,
        },
        {
          key: "now_to",
          label: "До сега",
          type: "checkbox",
          required: false,
        },
        {
          key: "mesec_to",
          label: "Месец до",
          type: "number",
          required: false,
          min: 1,
          max: 12,
        },
        {
          key: "godina_to",
          label: "Година до",
          type: "number",
          required: false,
          min: 1950,
          max: 2100,
        },
        {
          key: "name",
          label: "Наименование на програмата",
          type: "text",
          required: true,
          maxLength: 150,
        },
        {
          key: "position",
          label: "Позиция/роля",
          type: "text",
          required: true,
          maxLength: 150,
        },
        {
          key: "organization",
          label: "Организация",
          type: "text",
          required: true,
          maxLength: 150,
        },
        {
          key: "content",
          label: "Описание",
          type: "textarea",
          required: false,
        },
      ],
    },

    // 5.2. Участие в проекти (record_list)
    {
      subsectionId: "projects",
      sectionId: "section-5",
      type: "record_list",
      title: "Участие в проекти",
      description: "Образователни и научни проекти",
      order: 2,
      displayMode: "table",
      allowMultipleRecords: true,
      endpoint: {
        cmd: "projects",
        method: "POST",
      },
      fields: [
        {
          key: "mesec_from",
          label: "Месец от",
          type: "number",
          required: true,
          min: 1,
          max: 12,
        },
        {
          key: "godina_from",
          label: "Година от",
          type: "number",
          required: true,
          min: 1950,
          max: 2100,
        },
        {
          key: "now_to",
          label: "До сега",
          type: "checkbox",
          required: false,
        },
        {
          key: "mesec_to",
          label: "Месец до",
          type: "number",
          required: false,
          min: 1,
          max: 12,
        },
        {
          key: "godina_to",
          label: "Година до",
          type: "number",
          required: false,
          min: 1950,
          max: 2100,
        },
        {
          key: "name",
          label: "Наименование на проекта",
          type: "text",
          required: true,
          maxLength: 150,
        },
        {
          key: "position",
          label: "Позиция/роля",
          type: "text",
          required: true,
          maxLength: 150,
        },
        {
          key: "organization",
          label: "Организация",
          type: "text",
          required: true,
          maxLength: 150,
        },
        {
          key: "content",
          label: "Описание",
          type: "textarea",
          required: false,
        },
      ],
    },

    // 5.3. Научно-изследователска дейност (record_list)
    {
      subsectionId: "research",
      sectionId: "section-5",
      type: "record_list",
      title: "Научно-изследователска дейност",
      description: "Изследователски проекти и дейности",
      order: 3,
      displayMode: "table",
      allowMultipleRecords: true,
      endpoint: {
        cmd: "research",
        method: "POST",
      },
      fields: [
        {
          key: "mesec_from",
          label: "Месец от",
          type: "number",
          required: true,
          min: 1,
          max: 12,
        },
        {
          key: "godina_from",
          label: "Година от",
          type: "number",
          required: true,
          min: 1950,
          max: 2100,
        },
        {
          key: "now_to",
          label: "До сега",
          type: "checkbox",
          required: false,
        },
        {
          key: "mesec_to",
          label: "Месец до",
          type: "number",
          required: false,
          min: 1,
          max: 12,
        },
        {
          key: "godina_to",
          label: "Година до",
          type: "number",
          required: false,
          min: 1950,
          max: 2100,
        },
        {
          key: "name",
          label: "Наименование",
          type: "text",
          required: true,
          maxLength: 150,
        },
        {
          key: "position",
          label: "Позиция/роля",
          type: "text",
          required: true,
          maxLength: 150,
        },
        {
          key: "organization",
          label: "Организация",
          type: "text",
          required: true,
          maxLength: 150,
        },
        {
          key: "content",
          label: "Описание",
          type: "textarea",
          required: false,
        },
      ],
    },

    // 5.4. Мероприятия и събития (record_list)
    {
      subsectionId: "activities",
      sectionId: "section-5",
      type: "record_list",
      title: "Мероприятия и събития",
      description: "Участия в мероприятия и дейности",
      order: 4,
      displayMode: "table",
      allowMultipleRecords: true,
      endpoint: {
        cmd: "activities",
        method: "POST",
      },
      fields: [
        {
          key: "name",
          label: "Наименование",
          type: "text",
          required: true,
          maxLength: 150,
        },
        {
          key: "data",
          label: "Дата",
          type: "date",
          required: true,
        },
        {
          key: "content",
          label: "Описание",
          type: "textarea",
          required: false,
        },
      ],
    },

    // 5.5. Членство в организации (record_list)
    {
      subsectionId: "organizations",
      sectionId: "section-5",
      type: "record_list",
      title: "Членство в организации",
      description: "Професионални и обществени организации",
      order: 5,
      displayMode: "table",
      allowMultipleRecords: true,
      endpoint: {
        cmd: "organizations",
        method: "POST",
      },
      fields: [
        {
          key: "mesec_from",
          label: "Месец от",
          type: "number",
          required: true,
          min: 1,
          max: 12,
        },
        {
          key: "godina_from",
          label: "Година от",
          type: "number",
          required: true,
          min: 1950,
          max: 2100,
        },
        {
          key: "now_to",
          label: "До сега",
          type: "checkbox",
          required: false,
        },
        {
          key: "mesec_to",
          label: "Месец до",
          type: "number",
          required: false,
          min: 1,
          max: 12,
        },
        {
          key: "godina_to",
          label: "Година до",
          type: "number",
          required: false,
          min: 1950,
          max: 2100,
        },
        {
          key: "organization",
          label: "Организация",
          type: "text",
          required: true,
          maxLength: 150,
        },
      ],
    },

    // 5.6. Форуми и семинари (record_list)
    {
      subsectionId: "forums",
      sectionId: "section-5",
      type: "record_list",
      title: "Форуми и семинари",
      description: "Участия във форуми, семинари и конференции",
      order: 6,
      displayMode: "table",
      allowMultipleRecords: true,
      endpoint: {
        cmd: "forums",
        method: "POST",
      },
      fields: [
        {
          key: "data",
          label: "Дата",
          type: "date",
          required: true,
        },
        {
          key: "tema",
          label: "Тема",
          type: "text",
          required: true,
          maxLength: 255,
        },
        {
          key: "type",
          label: "Тип",
          type: "select",
          required: true,
          options: OPTIONS.FORUM_TYPES,
        },
        {
          key: "organization",
          label: "Организация",
          type: "text",
          required: true,
          maxLength: 150,
        },
        {
          key: "content",
          label: "Описание",
          type: "textarea",
          required: false,
        },
      ],
    },
  ],
};
